### ISSUE TITLE
Crash - Facebook - Android - 11.1.0

### ISSUE THREAD

**Issue by antonioduran** [tidev/ti.facebook#342]
Hello..Good afternoon / evening / morning.

It was gotten the following issue: The app is crashing when it is using the latest version of the module (11.1.0)
Working all good with the previous version (11.02)

Specs: 
```<module platform="android" version="11.1.0">facebook</module>```
Node: v14.17.0
Ti SDK: 10.1.1.GA
Device: Huawei P20 Pro 
Android Version: 10

It seems that it is something related about: `libfacebook.so`

`
2022-04-04 14:45:03.437 11839-11839/? I/.clmbty: Late-enabling -Xcheck:jni
2022-04-04 14:45:03.482 11839-11839/? E/.clmbty: Unknown bits set in runtime_flags: 0x8000
2022-04-04 14:45:03.484 11839-11839/? I/.clmbty: Reinit property: dalvik.vm.checkjni= false
2022-04-04 14:45:03.503 11839-11839/? W/re-initialized>: type=1400 audit(0.0:1286004): avc: denied { read } for pid=11839 name="u:object_r:mmi_prop:s0" dev="tmpfs" ino=12085 scontext=u:r:untrusted_app:s0:c54,c256,c512,c768 tcontext=u:object_r:mmi_prop:s0 tclass=file permissive=0
2022-04-04 14:45:03.507 11839-11839/? E/libc: Access denied finding property "runtime.mmitest.isrunning"
2022-04-04 14:45:03.511 11839-11839/? D/ActivityThread: Attach thread to application
2022-04-04 14:45:04.027 11839-11839/com.c.clmbty I/.clmbty: QarthPatchMonintor::Init
2022-04-04 14:45:04.027 11839-11839/com.c.clmbty I/.clmbty: QarthPatchMonintor::StartWatch
2022-04-04 14:45:04.028 11839-11839/com.c.clmbty I/.clmbty: QarthPatchMonintor::WatchPackage: /data/hotpatch/fwkhotpatch/
2022-04-04 14:45:04.028 11839-11839/com.c.clmbty I/.clmbty: QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/com.c.clmbty
2022-04-04 14:45:04.028 11839-11839/com.c.clmbty I/.clmbty: QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/all
2022-04-04 14:45:04.028 11839-11839/com.c.clmbty I/.clmbty: QarthPatchMonintor::Run
2022-04-04 14:45:04.028 11839-11858/com.c.clmbty I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.c.clmbty#10054#256
2022-04-04 14:45:04.029 11839-11873/com.c.clmbty I/.clmbty: QarthPatchMonintor::Reading
2022-04-04 14:45:04.029 11839-11873/com.c.clmbty I/.clmbty: QarthPatchMonintor::CheckNotifyEvent
2022-04-04 14:45:04.029 11839-11873/com.c.clmbty I/.clmbty: QarthPatchMonintor::CheckNotifyEvent before read
2022-04-04 14:45:04.030 11839-11858/com.c.clmbty I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.c.clmbty#10054#0
2022-04-04 14:45:04.045 11839-11839/com.c.clmbty I/TiApplication: (main) [0,0] checkpoint, app created.
2022-04-04 14:45:04.072 11839-11858/com.c.clmbty I/AwareBitmapCacher: init processName:com.c.clmbty pid=11839 uid=10054
2022-04-04 14:45:04.075 11839-11875/com.c.clmbty E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@3264b9
2022-04-04 14:45:04.076 11839-11875/com.c.clmbty E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@3b70fe
2022-04-04 14:45:04.152 11839-11839/com.c.clmbty W/com.facebook.UserSettingsManager: The value for AdvertiserIDCollectionEnabled is currently set to FALSE so you're sending app events without collecting Advertiser ID. This can affect the quality of your advertising and analytics results.
2022-04-04 14:45:04.166 11839-11880/com.c.clmbty D/HwFrameworkSecurityPartsFactory: HwFrameworkSecurityPartsFactory in.
2022-04-04 14:45:04.166 11839-11880/com.c.clmbty I/HwFrameworkSecurityPartsFactory: add HwFrameworkSecurityPartsFactory to memory.
2022-04-04 14:45:04.542 11839-11839/com.c.clmbty D/AndroidRuntime: Shutting down VM
2022-04-04 14:45:04.542 11839-11839/com.c.clmbty I/QarthLog: [PatchStore] createDisableExceptionQarthFile
2022-04-04 14:45:04.543 11839-11839/com.c.clmbty I/QarthLog: [PatchStore] create disable file for com.c.clmbty uid is 10054
2022-04-04 14:45:04.547 11839-11839/com.c.clmbty E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.c.clmbty, PID: 11839
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN2v88internal20CanHaveInternalFieldEi" referenced by "/data/app/com.c.clmbty-HiUQUuZJcCedLuhgKYsMUg==/base.apk!/lib/arm64-v8a/libfacebook.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:135)
        at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:109)
        at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:217)
        at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:112)
        at com.c.clmbty.MyCountyApplication.onCreate(MyCountyApplication.java:85)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1195)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7202)
        at android.app.ActivityThread.access$2200(ActivityThread.java:296)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
2022-04-04 14:45:04.550 11839-11839/com.c.clmbty I/.clmbty: System.exit called, status: 0
2022-04-04 14:45:04.550 11839-11839/com.c.clmbty I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
`

Thanks, and best,
Antonio Duran.

**Comment by antonioduran** [comment]
Hello...Good morning / afternoon / evening...

Recompiling the module did the job, so it is working again...Thanks...

`
android $ti build -p android --build-only
Titanium Command-Line Interface, CLI version 5.3.0, Titanium SDK version 10.1.1.GA
Copyright (c) 2012-2020, Appcelerator, Inc.  All Rights Reserved.

Please report bugs to http://jira.appcelerator.org/

4/4/2022, 3:57:29 PM

Operating System
  Name                        = macOS
  Version                     = 12.0.1
  Architecture                = 64bit
  # CPUs                      = 4
  Memory                      = 17179869184

Node.js
  Node.js Version             = 14.17.0
  npm Version                 = 6.14.13

Titanium CLI
  CLI Version                 = 5.3.0

Titanium SDK
  SDK Version                 = 10.1.1.GA
  SDK Path                    = /Users/tony/Library/Application Support/Titanium/mobilesdk/osx/10.1.1.GA
  Target Platform             = android

Command
  /usr/local/bin/node /usr/local/bin/ti build -p android --build-only

[INFO]  Assets Dir: /Users/tony/ti.facebook/assets
[INFO]  Documentation Dir: /Users/tony/ti.facebook/android/documentation
[INFO]  Example Dir: /Users/tony/ti.facebook/example
[INFO]  Platform Dir: /Users/tony/ti.facebook/platform
[INFO]  Resources Dir: /Users/tony/ti.facebook/Resources
[INFO]  Generating root project files
[INFO]  Generating gradle project: module
[INFO]  Building module
[INFO]  [GRADLE] Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
[INFO]  [GRADLE] 
[INFO]  [GRADLE] > Configure project :module
[INFO]  [GRADLE] Checking the license for package NDK (Side by side) 21.4.7075529 in /Users/tony/Library/Android/sdk/licenses
[INFO]  [GRADLE] License for package NDK (Side by side) 21.4.7075529 accepted.
[INFO]  [GRADLE] Preparing "Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)".
[INFO]  [GRADLE] "Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)" ready.
[INFO]  [GRADLE] Installing NDK (Side by side) 21.4.7075529 in /Users/tony/Library/Android/sdk/ndk/21.4.7075529
[INFO]  [GRADLE] "Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)" complete.
[INFO]  [GRADLE] "Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)" finished.
[INFO]  [GRADLE] 
[INFO]  [GRADLE] > Task :module:preBuild
[INFO]  [GRADLE] > Task :module:preReleaseBuild
[INFO]  [GRADLE] > Task :module:compileReleaseAidl NO-SOURCE
[INFO]  [GRADLE] > Task :module:compileReleaseRenderscript NO-SOURCE
[INFO]  [GRADLE] > Task :module:generateReleaseBuildConfig
[INFO]  [GRADLE] > Task :module:generateReleaseResValues
[INFO]  [GRADLE] > Task :module:generateReleaseResources
[INFO]  [GRADLE] > Task :module:packageReleaseResources
[INFO]  [GRADLE] > Task :module:parseReleaseLocalResources
[INFO]  [GRADLE] > Task :module:processReleaseManifest
[INFO]  [GRADLE] > Task :module:javaPreCompileRelease
[INFO]  [GRADLE] > Task :module:generateReleaseRFile
[INFO]  [GRADLE] > Task :module:configureNdkBuildRelease
[INFO]  [GRADLE] > Task :module:kaptGenerateStubsReleaseKotlin
[INFO]  [GRADLE] > Task :module:mergeReleaseJniLibFolders
[INFO]  [GRADLE] > Task :module:mergeReleaseShaders
[INFO]  [GRADLE] > Task :module:compileReleaseShaders NO-SOURCE
[INFO]  [GRADLE] > Task :module:generateReleaseAssets UP-TO-DATE
[INFO]  [GRADLE] > Task :module:packageReleaseAssets
[INFO]  [GRADLE] > Task :module:packageReleaseRenderscript NO-SOURCE
[INFO]  [GRADLE] > Task :module:prepareLintJarForPublish
[INFO]  [GRADLE] > Task :module:prepareReleaseArtProfile
[INFO]  [GRADLE] > Task :module:processReleaseJavaRes NO-SOURCE
[INFO]  [GRADLE] > Task :module:writeReleaseAarMetadata
[INFO]  [GRADLE] 
[INFO]  [GRADLE] > Task :module:kaptReleaseKotlin
[INFO]  [GRADLE] [KrollBindingGen] Running Kroll binding generator.
[INFO]  [GRADLE] [KrollBindingGen] Found binding for proxy LoginButton
[INFO]  [GRADLE] [KrollBindingGen] Found binding for proxy ActivityWorker
[INFO]  [GRADLE] [KrollBindingGen] Found binding for module Facebook
[INFO]  [GRADLE] Generating /Users/tony/ti.facebook/android/build/module/build/ti-generated/jni/facebook.ActivityWorkerProxy.h
[INFO]  [GRADLE] Generating /Users/tony/ti.facebook/android/build/module/build/ti-generated/jni/facebook.ActivityWorkerProxy.cpp
[INFO]  [GRADLE] Generating /Users/tony/ti.facebook/android/build/module/build/ti-generated/jni/facebook.TiFacebookModule.h
[INFO]  [GRADLE] Generating /Users/tony/ti.facebook/android/build/module/build/ti-generated/jni/facebook.TiFacebookModule.cpp
[INFO]  [GRADLE] Generating /Users/tony/ti.facebook/android/build/module/build/ti-generated/jni/facebook.LoginButtonProxy.h
[INFO]  [GRADLE] Generating /Users/tony/ti.facebook/android/build/module/build/ti-generated/jni/facebook.LoginButtonProxy.cpp
[INFO]  [GRADLE] 
[INFO]  [GRADLE] > Task :module:mergeReleaseResources
[INFO]  [GRADLE] > Task :module:compileReleaseKotlin
[INFO]  [GRADLE] 
[INFO]  [GRADLE] > Task :module:compileReleaseJavaWithJavac
[INFO]  [GRADLE] The following annotation processors are not incremental: kroll-apt.jar.
[INFO]  [GRADLE] Make sure all annotation processors are incremental to improve your build speed.
[ERROR] [GRADLE] /Users/tony/ti.facebook/android/src/facebook/TiFacebookModule.java:470: warning: [deprecation] WEB_VIEW_ONLY in LoginBehavior has been deprecated
[ERROR] [GRADLE] 				loginBehavior = LoginBehavior.WEB_VIEW_ONLY;
[ERROR] [GRADLE] 				                             ^
[ERROR] [GRADLE] 1 warning
[INFO]  [GRADLE] Running Titanium "generate-cpp-files.js" script.
[INFO]  [GRADLE] 
[INFO]  [GRADLE] > Task :module:buildNdkBuildRelease
[INFO]  [GRADLE] > Task :module:externalNativeBuildRelease
[INFO]  [GRADLE] > Task :module:mergeReleaseNativeLibs
[INFO]  [GRADLE] > Task :module:extractReleaseAnnotations
[INFO]  [GRADLE] > Task :module:stripReleaseDebugSymbols
[INFO]  [GRADLE] > Task :module:mergeReleaseGeneratedProguardFiles
[INFO]  [GRADLE] > Task :module:mergeReleaseConsumerProguardFiles
[INFO]  [GRADLE] > Task :module:copyReleaseJniLibsProjectAndLocalJars
[INFO]  [GRADLE] > Task :module:compileReleaseSources
[INFO]  [GRADLE] > Task :module:mergeReleaseJavaResource
[INFO]  [GRADLE] > Task :module:syncReleaseLibJars
[INFO]  [GRADLE] > Task :module:bundleReleaseAar
[INFO]  [GRADLE] > Task :module:verifyReleaseResources
[INFO]  [GRADLE] > Task :module:assembleRelease
[INFO]  [GRADLE] 
[INFO]  [GRADLE] BUILD SUCCESSFUL in 7m 50s
[INFO]  [GRADLE] 32 actionable tasks: 32 executed
[INFO]  [GRADLE] > Task :module:generatePomFileForTitaniumPublicationPublication
[INFO]  [GRADLE] > Task :module:publishTitaniumPublicationPublicationToMavenRepository
[INFO]  [GRADLE] > Task :module:publish
[INFO]  [GRADLE] 
[INFO]  [GRADLE] BUILD SUCCESSFUL in 2s
[INFO]  [GRADLE] 2 actionable tasks: 2 executed
[INFO]  Packaging the module
[INFO]  Creating module zip
[INFO]  Writing module zip: /Users/tony/ti.facebook/android/dist/facebook-android-11.1.0.zip
[INFO]  Project built successfully in 8m 9s 631ms`

Thanks, and best,
Antonio Duran...

**Comment by hansemannn** [comment]
@m1ga Can you swap the release artifact if possible?

**Comment by m1ga** [comment]
@antonioduran can you check this file please 
[facebook-android-11.1.0.zip](https://github.com/tidev/ti.facebook/files/8421784/facebook-android-11.1.0.zip)
if that works for you I'll swap the release binary

**Comment by antonioduran** [comment]
Hello @hansemannn @m1ga ...Good evening / morning...

It worked using the zip module.

I will be creating another issue in couple hours , but this is related about latest version of Facebook - iOS module latest version 12.0.0

Thanks, and best,
Antonio Duran...

**Comment by m1ga** [comment]
Thanks for the quick feedback 👍  I've changed the binary in the release tab so other users won't have that issue!
